// Generated by gencpp from file custom_msgs/TaskPath.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TASKPATH_H
#define CUSTOM_MSGS_MESSAGE_TASKPATH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct TaskPath_
{
  typedef TaskPath_<ContainerAllocator> Type;

  TaskPath_()
    : robotName()
    , currentWorkflowStep()
    , path()  {
    }
  TaskPath_(const ContainerAllocator& _alloc)
    : robotName(_alloc)
    , currentWorkflowStep(_alloc)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robotName_type;
  _robotName_type robotName;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _currentWorkflowStep_type;
  _currentWorkflowStep_type currentWorkflowStep;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::custom_msgs::TaskPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::TaskPath_<ContainerAllocator> const> ConstPtr;

}; // struct TaskPath_

typedef ::custom_msgs::TaskPath_<std::allocator<void> > TaskPath;

typedef boost::shared_ptr< ::custom_msgs::TaskPath > TaskPathPtr;
typedef boost::shared_ptr< ::custom_msgs::TaskPath const> TaskPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::TaskPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::TaskPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::TaskPath_<ContainerAllocator1> & lhs, const ::custom_msgs::TaskPath_<ContainerAllocator2> & rhs)
{
  return lhs.robotName == rhs.robotName &&
    lhs.currentWorkflowStep == rhs.currentWorkflowStep &&
    lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::TaskPath_<ContainerAllocator1> & lhs, const ::custom_msgs::TaskPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TaskPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TaskPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TaskPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TaskPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TaskPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TaskPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::TaskPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "970b44acb4bfcd0885f6e14494a46276";
  }

  static const char* value(const ::custom_msgs::TaskPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x970b44acb4bfcd08ULL;
  static const uint64_t static_value2 = 0x85f6e14494a46276ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::TaskPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/TaskPath";
  }

  static const char* value(const ::custom_msgs::TaskPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::TaskPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robotName\n"
"string currentWorkflowStep\n"
"geometry_msgs/Point[] path\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::custom_msgs::TaskPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::TaskPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robotName);
      stream.next(m.currentWorkflowStep);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::TaskPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::TaskPath_<ContainerAllocator>& v)
  {
    s << indent << "robotName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robotName);
    s << indent << "currentWorkflowStep: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.currentWorkflowStep);
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TASKPATH_H
